In [1]:
import os
import numpy as np
import pandas as pd
## import matplotlib.pyplot as plt
## %matplotlib inline
## import seaborn as sns
import sqlalchemy
from sqlalchemy import text
from datetime import datetime
pd.set_option('display.max_columns', None)

In [8]:
share_path = '//10.10.32.223/Risk Management/Analytics and Forecasting/Global PP Metrics/Merchant Portfolio (Dustin)/'
local_path = 'C:/Users/dustinoneil/Desktop/Global Payment Processing Metrics/'

# Irvine

In [3]:
print(datetime.now().strftime("%H:%M:%S"), "  --  Start reading Irvine data")
Irvine = pd.read_csv(local_path + 'Irvine_Merchant_Portfolio_rev_3.2 - add zeus CRM.csv'
            , dtype={'Month' : 'str'})

09:14:01   --  Start reading Irvine data

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (5) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [4]:
Irvine_1 = Irvine.copy()
#Irvine_1 = Irvine_1.loc[~Irvine_1['Month'].isna()]
Irvine_1 = Irvine_1.rename(columns={"Month":"YM"})
Irvine_1['Month'] = pd.to_datetime(Irvine_1['Date'])
Irvine_1['Business Country'] = 'US'
Irvine_1 = Irvine_1.drop(columns=['Date'])

status_dict_Irvine_1 = {'MS - Cancellation':'Cancelled', 
                        'MS - Active':'Active'}
Irvine_1['current Status'] = Irvine_1['current Status'].replace(status_dict_Irvine_1)

Irvine_1['Business Group'] = 'Meritus'
#Irvine_1 = Irvine_1.drop(columns=['Activation Flag.1']) #can remove the duplicate column from the SQL
Irvine_1

,MID,Business DBA Name,Business Legal Name,current Status,MCC,CRM_VendorUID,Partner DBA,Bank,BIN,Office Name,Active Month Max,Inactive Month Max,Cancel Month Max,CC Avg Ticket Value,CU Approved Volume,Payment Category,Closure Reason Name,Closure Reason Description,YM,Sales Count,Sales Volume,Refund Count,Refund Volume,CB Count,CB Volume,Fraud Volume,Fraud Count,Activation Flag,Activation Flag.1,Inactive Flag -1,Cancelation Flag,Cancelation Flag -1,Actively Processing,Tenure_Months,Reserve Amount,Month,Business Country,Business Group
0,3286000000008060,Active Ride Shop 1002,Active Sports Lifestyle USA LLC,Cancelled,5699.0,NaN,Pro Music Group,Woodforest,328600,Irvine (US),201206.0,NaN,201506.0,70.0,200000.0,CNP,Inadequate Products/Services,Products or services are unable to accommodate...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,will add,will add,0,0,0,0,0,0,0,NaN,NaT,US,Meritus
1,3286000000008094,Two Trees Inn,Mashantucket Pequot Gaming Enterprise,Cancelled,7011.0,NaN,Primary Merchant Solutions,Woodforest,328600,Irvine (US),201211.0,NaN,201703.0,500.0,375000.0,CP,Risk - Collections,"Collections due to chargebacks, credits, fees,...",201601,1507.0,260529.73,47.0,6000.07,3.0,226.18,will add,will add,0,0,0,0,0,1,5,NaN,2016-01-01,US,Meritus
2,3286000000008094,Two Trees Inn,Mashantucket Pequot Gaming Enterprise,Cancelled,7011.0,NaN,Primary Merchant Solutions,Woodforest,328600,Irvine (US),201211.0,NaN,201703.0,500.0,375000.0,CP,Risk - Collections,"Collections due to chargebacks, credits, fees,...",201602,1718.0,323940.25,16.0,1659.23,3.0,45.88,will add,will add,0,0,0,0,0,1,5,NaN,2016-02-01,US,Meritus
3,3286000000008094,Two Trees Inn,Mashantucket Pequot Gaming Enterprise,Cancelled,7011.0,NaN,Primary Merchant Solutions,Woodforest,328600,Irvine (US),201211.0,NaN,201703.0,500.0,375000.0,CP,Risk - Collections,"Collections due to chargebacks, credits, fees,...",201603,1631.0,344404.09,41.0,4751.12,2.0,526.41,will add,will add,0,0,0,0,0,1,5,NaN,2016-03-01,US,Meritus
4,3286000000008094,Two Trees Inn,Mashantucket Pequot Gaming Enterprise,Cancelled,7011.0,NaN,Primary Merchant Solutions,Woodforest,328600,Irvine (US),201211.0,NaN,201703.0,500.0,375000.0,CP,Risk - Collections,"Collections due to chargebacks, credits, fees,...",201604,1577.0,307170.60,34.0,4624.34,5.0,552.49,will add,will add,0,0,0,0,0,1,5,NaN,2016-04-01,US,Meritus
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564377,9109000089863889,Merrick Mirror Hosting,Merrick Mirror Hosting Inc,Cancelled,4816.0,NaN,"DL Ventures, Inc",BMO - Harris,910900,Irvine (US),201605.0,NaN,201804.0,100.0,99000.0,CNP,Risk - Unacceptable Risk Level,Risk - Unacceptable Risk Level,201801,1.0,184.78,1.0,268.35,NaN,NaN,will add,will add,0,0,0,0,0,1,22,NaN,2018-01-01,US,Meritus
564378,9109000089863889,Merrick Mirror Hosting,Merrick Mirror Hosting Inc,Cancelled,4816.0,NaN,"DL Ventures, Inc",BMO - Harris,910900,Irvine (US),201605.0,NaN,201804.0,100.0,99000.0,CNP,Risk - Unacceptable Risk Level,Risk - Unacceptable Risk Level,201802,1917.0,47560.71,1.0,9.46,NaN,NaN,will add,will add,0,0,0,0,0,1,22,NaN,2018-02-01,US,Meritus
564379,9109000089863889,Merrick Mirror Hosting,Merrick Mirror Hosting Inc,Cancelled,4816.0,NaN,"DL Ventures, Inc",BMO - Harris,910900,Irvine (US),201605.0,NaN,201804.0,100.0,99000.0,CNP,Risk - Unacceptable Risk Level,Risk - Unacceptable Risk Level,201803,1969.0,44466.53,1.0,8.41,9.0,1040.88,will add,will add,0,0,0,0,0,1,22,NaN,2018-03-01,US,Meritus
564380,9109000089863889,Merrick Mirror Hosting,Merrick Mirror Hosting Inc,Cancelled,4816.0,NaN,"DL Ventures, Inc",BMO - Harris,910900,Irvine (US),201605.0,NaN,201804.0,100.0,99000.0,CNP,Risk - Unacceptable Risk Level,Risk - Unacceptable Risk Level,201804,5.0,2712.00,NaN,NaN,NaN,NaN,will add,will add,0,0,0,1,-1,1,22,NaN,2018-04-01,US,Meritus
564381,9109000089863889,Merrick Mirror Hosting,Merrick Mirror Hosting Inc,Cancelled,4816.0,NaN,"DL Ventures, Inc",BMO - Harris,910900,Irvine (US),201605.0,NaN,201804.0,100.0,99000.0,CNP,Risk - Unacceptable Risk Level,Risk - Unacceptable Risk Level,201805,NaN,NaN,NaN,NaN,1.0,-8.74,will add,will add,0,0,0,0,0,0,22,NaN,2018-05-01,US,Meritus

In [5]:
Irvine_1['Tenure_Months'].unique()

array([  0,   5,   1,  14,  11,   2,   3,  24,  51,  69,  22,  57,  35,
         7,  28,  37,  41,  63,  61,  18,  62,  31,  48,  32,  55,   6,
        60,  42,  50,  58,  20,  10,  46,  15,   4,  44,  19,  59,  43,
         9,  25,  36,  52,  26,  33,  30,  54,  29,  13,  21,  40,  49,
        39,  17,   8,  27,  23,  45,  47,  12,  16,  34,  70,  53,  56,
        68,  65,  38,  66,  67,  64, 134,  84], dtype=int64)

In [10]:
Irvine_1['current Status'].unique()

array(['Cancelled', 'Active', 'MS - Inactive',
       'MS - Conducted Welcome Call'], dtype=object)

# UK and Montreal
# Talk to Denise O about BINs to get to processor

In [11]:
#UK Montreal 
print(datetime.now().strftime("%H:%M:%S"), "  --  Start reading UK and Montreal data")
UK_Montreal_2019 = pd.read_excel(share_path + 'Portfolio Metrics - Dustin UK MTL 2019 v2.xlsx')
UK_Montreal_2020 = pd.read_excel(share_path + 'Portfolio Metrics - Dustin UK MTL 2020 v2.xlsx')
UK_Montreal_2021 = pd.read_excel(share_path + 'Portfolio Metrics - Dustin UK MTL 2021 v2.xlsx')

09:33:31   --  Start reading UK and Montreal data

In [12]:
UK_Montreal = pd.concat([UK_Montreal_2019, UK_Montreal_2020, UK_Montreal_2021], axis=0)  #add 
UK_Montreal

,ACCOUNT_ID,BUSINESSDBANAME,BUSINESSLEGALNAME,MCC,CURRENTSTATUS,MCCDESCRIPTION,PARTNERDBA,ISV_PARTNER_NAME,BANK,BIN,OFFICENAME,ACTIVE_MONTH_MAX,INACTIVE_MONTH_MAX,CANCEL_MONTH,CANCEL_DATE,CC_AVG_TICKET_VALUE,CU_APPROVED_VOLUME,PAYMENT_CATEGORY,Closure Reason Name,Closure Reason Description,MNTH,Sales Count,Sales Volume,Refund Count,Refund Volume,CB Count,CB Volume,Fraud Volume,Fraud Count,Activation Flag,Inactive Flag -1,Cancelation Flag,Cancelation Flag -1,Actively Processing,Tenure_Months,BUSINESSCOUNTRY,BUSINESSGROUP
0,500046,Ad Mats Corp. (Usd),Ad Mats Corp. (Usd),5941.0,Closed,SPORTING GOODS STORES,"77778075 - AAA-No Agent( ,/)",NaN,MOC,NaN,Montreal,2002-11-01,NaN,2020-07-01,2020-07-20 16:35:08,NaN,-999,NaN,NaN,NaN,2019-01-01,0.0,0.00000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CANADA,IES
1,500046,Ad Mats Corp. (Usd),Ad Mats Corp. (Usd),5941.0,Closed,SPORTING GOODS STORES,"77778075 - AAA-No Agent( ,/)",NaN,MOC,NaN,Montreal,2002-11-01,NaN,2020-07-01,2020-07-20 16:35:08,NaN,-999,NaN,NaN,NaN,2019-02-01,0.0,0.00000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CANADA,IES
2,500046,Ad Mats Corp. (Usd),Ad Mats Corp. (Usd),5941.0,Closed,SPORTING GOODS STORES,"77778075 - AAA-No Agent( ,/)",NaN,MOC,NaN,Montreal,2002-11-01,NaN,2020-07-01,2020-07-20 16:35:08,NaN,-999,NaN,NaN,NaN,2019-03-01,0.0,0.00000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CANADA,IES
3,500046,Ad Mats Corp. (Usd),Ad Mats Corp. (Usd),5941.0,Closed,SPORTING GOODS STORES,"77778075 - AAA-No Agent( ,/)",NaN,MOC,NaN,Montreal,2002-11-01,NaN,2020-07-01,2020-07-20 16:35:08,NaN,-999,NaN,NaN,NaN,2019-04-01,0.0,0.00000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CANADA,IES
4,500046,Ad Mats Corp. (Usd),Ad Mats Corp. (Usd),5941.0,Closed,SPORTING GOODS STORES,"77778075 - AAA-No Agent( ,/)",NaN,MOC,NaN,Montreal,2002-11-01,NaN,2020-07-01,2020-07-20 16:35:08,NaN,-999,NaN,NaN,NaN,2019-05-01,0.0,0.00000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CANADA,IES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321770,1003073224,cc - Fraser Arms,Second Street Fund Inc.,6513.0,Open,REAL ESTATE AGENTS AND MANAGERS-RENTALS,"77778075 - AAA-No Agent( ,/)",Rentmoola - Propertii,PET,NaN,Montreal,2021-10-01,NaN,NaT,NaT,NaN,6250,NaN,NaN,NaN,2021-10-01,4.0,5174.97260,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CANADA,IES
321771,1003073244,cc - McNiven Place,Second Street Fund Inc.,6513.0,Open,REAL ESTATE AGENTS AND MANAGERS-RENTALS,"77778075 - AAA-No Agent( ,/)",Rentmoola - Propertii,PET,NaN,Montreal,2021-10-01,NaN,NaT,NaT,NaN,6250,NaN,NaN,NaN,2021-10-01,4.0,3980.32467,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CANADA,IES
321772,1003073254,cc - Ciara Manor,Second Street Fund Inc.,6513.0,Open,REAL ESTATE AGENTS AND MANAGERS-RENTALS,"77778075 - AAA-No Agent( ,/)",Rentmoola - Propertii,PET,NaN,Montreal,2021-10-01,NaN,NaT,NaT,NaN,6250,NaN,NaN,NaN,2021-10-01,2.0,2736.91560,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CANADA,IES
321773,1003073304,cc - Fraser Tower,Second Street Fund Inc.,6513.0,Open,REAL ESTATE AGENTS AND MANAGERS-RENTALS,"77778075 - AAA-No Agent( ,/)",Rentmoola - Propertii,PET,NaN,Montreal,2021-10-01,NaN,NaT,NaT,NaN,6250,NaN,NaN,NaN,2021-10-01,5.0,5269.34900,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CANADA,IES
321774,1003073344,Cardinal Sports Academy Ltd.,Cardinal Sports Academy,8299.0,Open,SCHOOLS + EDUCATIONAL SVC-NOT ELSEWHERE CLASSI...,77778063 - Softerware (Doug Schoenberg)( Peopl...,Softerware,PET,NaN,Montreal,2021-10-01,NaN,NaT,NaT,NaN,14583,NaN,NaN,NaN,2021-10-01,0.0,0.00000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CANADA,IES

In [13]:
UK_Montreal_1 = UK_Montreal.copy()
UK_Montreal_1 = UK_Montreal_1.rename(columns={
                                    "ACCOUNT_ID":"MID",
                                    "BUSINESSDBANAME": "Business DBA Name", 
                                    "BUSINESSLEGALNAME": "Business Legal Name",
                                    "CURRENTSTATUS": "current Status",
                                    "PARTNERDBA": "Partner DBA",
                                    "OFFICENAME": "Office Name",
                                    "BANK": "Bank", 
                                    "BUSINESSCOUNTRY": "Business Country", 
                                    "BUSINESSGROUP" : "Business Group", 
                                    "MNTH":"Month", 
                                    "ACTIVE_MONTH_MAX":"Active Month Max",
                                    "INACTIVE_MONTH_MAX":"Inactive Month Max",
                                    "CC_AVG_TICKET_VALUE":"CC Avg Ticket Value",
                                    "CU_APPROVED_VOLUME":"CU Approved Volume",
                                    "PAYMENT_CATEGORY":"Payment Category", 
                                    "CANCEL_DATE": "Cancel Month Max"
                                   }) #inplace = True

UK_Montreal_1 = UK_Montreal_1.drop(columns=['MCCDESCRIPTION', 'Tenure_Months', 'CANCEL_MONTH'])
UK_Montreal_1["MID"] = UK_Montreal_1["MID"].astype(str)
UK_Montreal_1["YM"] = UK_Montreal_1["Month"].dt.strftime('%Y') + UK_Montreal_1["Month"].dt.strftime('%m')
UK_Montreal_1["Active Month Max"] = UK_Montreal_1["Active Month Max"].dt.strftime('%Y') + UK_Montreal_1["Active Month Max"].dt.strftime('%m')
#UK_Montreal_1["Inactive Month Max"] = 
UK_Montreal_1["Cancel Month Max"] = UK_Montreal_1["Cancel Month Max"].dt.strftime('%Y') + UK_Montreal_1["Cancel Month Max"].dt.strftime('%m')


#Flags
UK_Montreal_1["Activation Flag"] = (UK_Montreal_1["Active Month Max"] == UK_Montreal_1["YM"]).astype('int')
#UK_Montreal_1["Inactive Flag -1"] = 
UK_Montreal_1["Cancelation Flag"] = (UK_Montreal_1["Cancel Month Max"] == UK_Montreal_1["YM"]).astype('int')
UK_Montreal_1["Cancelation Flag -1"] = (UK_Montreal_1["Cancel Month Max"] == UK_Montreal_1["YM"]).astype('int')*-1

UK_Montreal_1["Actively Processing"] = (UK_Montreal_1['Sales Volume'] >= 50).astype('int')
UK_Montreal_1['Tenure_Months'] = UK_Montreal_1[["MID", "Actively Processing"]].groupby('MID').transform('sum')

status_dict = {'Closed': 'Cancelled', 'Open': 'Active'}
UK_Montreal_1['current Status'] = UK_Montreal_1['current Status'].replace(status_dict)
UK_Montreal_1

,MID,Business DBA Name,Business Legal Name,MCC,current Status,Partner DBA,ISV_PARTNER_NAME,Bank,BIN,Office Name,Active Month Max,Inactive Month Max,Cancel Month Max,CC Avg Ticket Value,CU Approved Volume,Payment Category,Closure Reason Name,Closure Reason Description,Month,Sales Count,Sales Volume,Refund Count,Refund Volume,CB Count,CB Volume,Fraud Volume,Fraud Count,Activation Flag,Inactive Flag -1,Cancelation Flag,Cancelation Flag -1,Actively Processing,Business Country,Business Group,YM,Tenure_Months
0,500046,Ad Mats Corp. (Usd),Ad Mats Corp. (Usd),5941.0,Cancelled,"77778075 - AAA-No Agent( ,/)",NaN,MOC,NaN,Montreal,200211,NaN,202007,NaN,-999,NaN,NaN,NaN,2019-01-01,0.0,0.00000,0.0,0.0,NaN,NaN,NaN,NaN,0,NaN,0,0,0,CANADA,IES,201901,0
1,500046,Ad Mats Corp. (Usd),Ad Mats Corp. (Usd),5941.0,Cancelled,"77778075 - AAA-No Agent( ,/)",NaN,MOC,NaN,Montreal,200211,NaN,202007,NaN,-999,NaN,NaN,NaN,2019-02-01,0.0,0.00000,0.0,0.0,NaN,NaN,NaN,NaN,0,NaN,0,0,0,CANADA,IES,201902,0
2,500046,Ad Mats Corp. (Usd),Ad Mats Corp. (Usd),5941.0,Cancelled,"77778075 - AAA-No Agent( ,/)",NaN,MOC,NaN,Montreal,200211,NaN,202007,NaN,-999,NaN,NaN,NaN,2019-03-01,0.0,0.00000,0.0,0.0,NaN,NaN,NaN,NaN,0,NaN,0,0,0,CANADA,IES,201903,0
3,500046,Ad Mats Corp. (Usd),Ad Mats Corp. (Usd),5941.0,Cancelled,"77778075 - AAA-No Agent( ,/)",NaN,MOC,NaN,Montreal,200211,NaN,202007,NaN,-999,NaN,NaN,NaN,2019-04-01,0.0,0.00000,0.0,0.0,NaN,NaN,NaN,NaN,0,NaN,0,0,0,CANADA,IES,201904,0
4,500046,Ad Mats Corp. (Usd),Ad Mats Corp. (Usd),5941.0,Cancelled,"77778075 - AAA-No Agent( ,/)",NaN,MOC,NaN,Montreal,200211,NaN,202007,NaN,-999,NaN,NaN,NaN,2019-05-01,0.0,0.00000,0.0,0.0,NaN,NaN,NaN,NaN,0,NaN,0,0,0,CANADA,IES,201905,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321770,1003073224,cc - Fraser Arms,Second Street Fund Inc.,6513.0,Active,"77778075 - AAA-No Agent( ,/)",Rentmoola - Propertii,PET,NaN,Montreal,202110,NaN,NaN,NaN,6250,NaN,NaN,NaN,2021-10-01,4.0,5174.97260,0.0,0.0,NaN,NaN,NaN,NaN,1,NaN,0,0,1,CANADA,IES,202110,1
321771,1003073244,cc - McNiven Place,Second Street Fund Inc.,6513.0,Active,"77778075 - AAA-No Agent( ,/)",Rentmoola - Propertii,PET,NaN,Montreal,202110,NaN,NaN,NaN,6250,NaN,NaN,NaN,2021-10-01,4.0,3980.32467,0.0,0.0,NaN,NaN,NaN,NaN,1,NaN,0,0,1,CANADA,IES,202110,1
321772,1003073254,cc - Ciara Manor,Second Street Fund Inc.,6513.0,Active,"77778075 - AAA-No Agent( ,/)",Rentmoola - Propertii,PET,NaN,Montreal,202110,NaN,NaN,NaN,6250,NaN,NaN,NaN,2021-10-01,2.0,2736.91560,0.0,0.0,NaN,NaN,NaN,NaN,1,NaN,0,0,1,CANADA,IES,202110,1
321773,1003073304,cc - Fraser Tower,Second Street Fund Inc.,6513.0,Active,"77778075 - AAA-No Agent( ,/)",Rentmoola - Propertii,PET,NaN,Montreal,202110,NaN,NaN,NaN,6250,NaN,NaN,NaN,2021-10-01,5.0,5269.34900,0.0,0.0,NaN,NaN,NaN,NaN,1,NaN,0,0,1,CANADA,IES,202110,1
321774,1003073344,Cardinal Sports Academy Ltd.,Cardinal Sports Academy,8299.0,Active,77778063 - Softerware (Doug Schoenberg)( Peopl...,Softerware,PET,NaN,Montreal,202110,NaN,NaN,NaN,14583,NaN,NaN,NaN,2021-10-01,0.0,0.00000,0.0,0.0,NaN,NaN,NaN,NaN,1,NaN,0,0,0,CANADA,IES,202110,0

In [14]:
UK_Montreal_1['Bank'].unique()

array(['MOC', 'PET', 'MER', 'VAN', 'AIB', 'BOV', 'OPL', 'NAB', 'BBVA'],
      dtype=object)

In [15]:
#str replace works but I'd like to use map instead 
#UK_Montreal_1['current Status'] = UK_Montreal_1['current Status'].str.replace('Closed', 'MS - Cancellation')
#UK_Montreal_1['current Status'] = UK_Montreal_1['current Status'].str.replace('Open', 'MS - Active')
UK_Montreal_1['current Status'].unique()

array(['Cancelled', 'Active'], dtype=object)

In [16]:
#Alternate methods 

#UK_Montreal_1["YM"].dt.year.astype(str) + UK_Montreal_1["MNTH"].dt.month.astype(str)
#UK_Montreal_1["Actively Processing"] = UK_Montreal_1['Sales Volume'].ge(50).astype('int') #ge is equivalent to >=

#Tenure_Months
#I found 3 methods to perform this. The better methods generate a series on which to work

#1 Transform method: Generate a sub-df which is a series, MID is the index, groupby and transform sum
    #used above 
    
#2 Map method
    #UK_Montreal_1['Tenure_Months_2'] = UK_Montreal_1['MID'].map(UK_Montreal_1.groupby('MID')['Actively Processing'].sum())

#3 Change index method 
    #More complicated, can be done easier
    #changes the index to MID and uses Group by.sum()...sum() sums that column on the index
    #UK_Montreal_1 = UK_Montreal_1.set_index('MID')
    #UK_Montreal_1 = UK_Montreal_1.assign(Tenure_Months_3 = UK_Montreal_1["Actively Processing"].groupby(["MID"]).sum())
    #UK_Montreal_1 = UK_Montreal_1.reset_index()

# WLV

In [17]:
#Houston and WLV are US acq Business GROUP
#I don't know how to get Business Unit

#WLV
print(datetime.now().strftime("%H:%M:%S"), "  --  Start reading WLV data")
WLV_2019 = pd.read_excel(share_path + 'WLV Processing 2019.xlsx',
                    #nrows = 100, 
                    sheet_name='Sheet1', #will have to iterate through them, or explicitly name them
                    converters={'MID':str, 'FirstProcessDate':pd.to_datetime, 
                                'ClosureDate':pd.to_datetime, 'month':pd.to_datetime}) #'month':str,

WLV_2020 = pd.read_excel(share_path + 'WLV Processing 2020.xlsx',
                    #nrows = 100, 
                    sheet_name='Sheet1', #will have to iterate through them, or explicitly name them
                    converters={'MID':str, 'FirstProcessDate':pd.to_datetime, 
                                'ClosureDate':pd.to_datetime, 'month':pd.to_datetime}) #'month':str,

WLV_2021 = pd.read_excel(share_path + 'WLV Processing 2021.xlsx',
                    #nrows = 100, 
                    sheet_name='Sheet1', #will have to iterate through them, or explicitly name them
                    converters={'MID':str, 'FirstProcessDate':pd.to_datetime, 
                                'ClosureDate':pd.to_datetime, 'month':pd.to_datetime}) #'month':str,

09:43:39   --  Start reading WLV data

In [18]:
WLV = pd.concat([WLV_2019, WLV_2020, WLV_2021], axis=0)  #add WLV_2019,

In [19]:
WLV_1 = WLV.copy()
WLV_1 = WLV_1.rename(columns={
                            #"ACCOUNT_ID":"MID",
                            "MerchantDBA": "Business DBA Name", 
                            "MerchantLegal": "Business Legal Name",
                            "AccountStatus": "current Status",
                            "Partner": "Partner DBA",
                            "Office": "Office Name",
                            "AcquiringBank": "Bank", 
                            #"BUSINESSCOUNTRY": "Business Country", 
                            "BusinessGroup" : "Business Group", 
                            "month":"Month", 
                            "FirstProcessDate":"Active Month Max",
                            #"INACTIVE_MONTH_MAX":"Inactive Month Max",
                            "ClosureDate":"Cancel Month Max",
                            "CCApprovedAverageTicket":"CC Avg Ticket Value",
                            "CCApprovedVolume":"CU Approved Volume",
                            "CP/CNPMerchant":"Payment Category", 
                            "VisaSaleCount":"Sales Count",
                            "VisasSaleAmount":"Sales Volume",
                            "VisaReturnCount":"Refund Count",
                            "VisaReturnAmount":"Refund Volume", 
                            "Chargebackcount":"CB Count", 
                            "ChargebackAmount":"CB Volume",
                            "ClosureReason": "Closure Reason Name"
                           })

#WLV_1 = WLV_1.drop(columns=['ISV_PARTNER_NAME'])

#WLV_1["Active Month Max"]= pd.to_datetime(WLV_1["Active Month Max"])
#WLV_1["Cancel Month Max"]= pd.to_datetime(WLV_1["Cancel Month Max"])
WLV_1["Active Month Max"] = WLV_1["Active Month Max"].dt.strftime('%Y') + WLV_1["Active Month Max"].dt.strftime('%m')
WLV_1["Cancel Month Max"] = WLV_1["Cancel Month Max"].dt.strftime('%Y') + WLV_1["Cancel Month Max"].dt.strftime('%m')

#Flags
WLV_1["YM"] = WLV_1["Month"].dt.strftime('%Y') + WLV_1["Month"].dt.strftime('%m')
WLV_1["Activation Flag"] = (WLV_1["Active Month Max"] == WLV_1["YM"]).astype('int')
#WLV_1["Inactive Flag -1"] = 
WLV_1["Cancelation Flag"] = (WLV_1["Cancel Month Max"] == WLV_1["YM"]).astype('int')
WLV_1["Cancelation Flag -1"] = (WLV_1["Cancel Month Max"] == WLV_1["YM"]).astype('int')*-1

WLV_1["Actively Processing"] = (WLV_1['Sales Volume'] >= 50).astype('int')
WLV_1['Tenure_Months'] = WLV_1[["MID", "Actively Processing"]].groupby('MID').transform('sum')

WLV_1['Business Country'] = 'US'
WLV_1['Business Group'] = 'iPayment'
#WLV_1['Office Name'] = 'West Lake Village'
#WLV_1['Month'] = pd.to_datetime(WLV_1['YM'].str[0:4] + '-' + WLV_1['YM'].str[4:6]+  '-01')
WLV_1['Refund Volume'] = WLV_1['Refund Volume']*-1
WLV_1['CB Volume'] = WLV_1['CB Volume']*-1

status_dict_WLV = {0: 'Cancelled', 1: 'Active'}
WLV_1['current Status'] = WLV_1['current Status'].replace(status_dict_WLV)

WLV_1

,MID,Business Legal Name,Business DBA Name,Business Group,Office Name,BIN,Bank,ISO,Partner DBA,SalesAgent,MCC,Payment Category,Active Month Max,Cancel Month Max,Closure Reason Name,CU Approved Volume,CC Avg Ticket Value,current Status,Month,Sales Count,Sales Volume,Refund Count,Refund Volume,CB Count,CB Volume,YM,Activation Flag,Cancelation Flag,Cancelation Flag -1,Actively Processing,Tenure_Months,Business Country
0,4200091110000880,FIRST DIRECT CORP.,FIRST DIRECT CORP.,iPayment,WLV.iPayment,420009,BBVA,IPIHOUSE::IPI House,a7001::John Kennedy,A00 ::IPAYMENTS IPMT,5734,CP,201401,NaN,NaN,25000.0,750.0,Active,2019-01-01,1.0,75.00,1.0,75.0,NaN,NaN,201901,0,0,0,1,2,US
1,4200091110037296,CONNECTION TECH COMMUNICATIONS,CONNECTION TECH COMMUNICATIONS,iPayment,WLV.iPayment,420009,BBVA,"DSHO04::CALPIAN COMMERCE, INC",A42 ::Dave Shoemaker,337 ::CHRIS KOHUT,4814,CP,201401,NaN,NaN,15000.0,50.0,Active,2019-01-01,17.0,693.71,0.0,-0.0,NaN,NaN,201901,0,0,0,1,29,US
2,4200091110044037,"THE CRUISE DEPOT, INC.","THE CRUISE DEPOT, INC.",iPayment,WLV.iPayment,420009,BBVA,EODE05::Eric IPT-Odegard,A40::Eric IPTOdegard,004 ::TINA ST. AMAND,4722,CP,201312,197001,102::NOC-NOTICE OF CHG,30000.0,425.0,Cancelled,2019-01-01,7.0,3251.18,0.0,-0.0,1.0,70.0,201901,0,0,0,1,17,US
3,4200097990003589,ZONK DESIGNS INC,SNOOZER BODY PILLOWS,iPayment,WLV.iPayment,420009,BBVA,IPIHOUSE::IPI House,a7001::John Kennedy,H00 ::SHAWN SKELTON,5719,CP,NaN,197001,019::SOLD BUSINESS,25000.0,600.0,Cancelled,2019-01-01,11.0,1363.11,0.0,-0.0,NaN,NaN,201901,0,0,0,1,2,US
4,4200098980002805,"BODYVED, INC.",BODYVED,iPayment,WLV.iPayment,420009,BBVA,IPIHOUSE::IPI House,a7001::John Kennedy,A00 ::IPAYMENTS IPMT,7299,CP,201401,NaN,NaN,15000.0,175.0,Active,2019-01-01,49.0,8560.00,0.0,-0.0,NaN,NaN,201901,0,0,0,1,33,US
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519273,4228997800000221,A & W Oil & Tire Company Inc,A & W One Stop,iPayment,WLV.PCS,422899,BBVA,"PCS-2640::Claude Godfrey Enterprises, INC","PCSA-2676::Claude Godfrey Enterprises, INC- PMA",PCSA-2676-989::Claude Godfrey-PMA,7542,CP,201703,NaN,NaN,50000.0,50.0,Active,2021-10-01,71.0,656.00,0.0,-0.0,NaN,NaN,202110,0,0,0,1,24,US
519274,4431637061000001,Joelle Team INC,D 'N A Smoke Shop,iPayment,WLV.PCS,443163,Merrick Bank,PCS-3004::Direct Processing Inc,TSMPCS-3004::Direct Processing Inc,TSMPCS-3004-001::Direct Processing Inc,5993,CP,202108,NaN,NaN,60000.0,300.0,Active,2021-10-01,58.0,1343.93,0.0,-0.0,NaN,NaN,202110,0,0,0,1,3,US
519275,4228997800000205,Jeffery Hatcher,Jeffery Hatcher Sole Proprietorship,iPayment,WLV.PCS,422899,BBVA,PCS-2001::PCS House Account,PCSA-3301::House- Fergi Fergus,PCSA-3301-2075::Fergi Fergus,5542,CP,201701,NaN,NaN,25000.0,100.0,Active,2021-10-01,14.0,1192.93,0.0,-0.0,NaN,NaN,202110,0,0,0,1,34,US
519276,4431632110007719,Hernando Sportsmans Club Inc,Hernando Sportsmans Club,iPayment,WLV.PCS,443163,Merrick Bank,PCS-3431::Sindra Ridge,TSM3431B::Ridge,TSM3431B-001::Sindra Ridge,7999,CP,201808,NaN,NaN,25000.0,75.0,Active,2021-10-01,361.0,15196.52,1.0,110.0,NaN,NaN,202110,0,0,0,1,34,US
519277,4431637060000036,D&PUSA2 INC,Smokin Joes,iPayment,WLV.PCS,443163,Merrick Bank,PCS-2001::PCS House Account,TSM07366::PCS House Merrick Bank,TSM07366-006::Michelle Barringer,5993,CP,202110,NaN,NaN,50000.0,25.0,Active,2021-10-01,91.0,3405.02,0.0,-0.0,NaN,NaN,202110,1,0,0,1,1,US

In [20]:
WLV_1['current Status'].unique()

array(['Active', 'Cancelled'], dtype=object)

In [21]:
WLV_1['Tenure_Months'].unique()

array([ 2, 29, 17, 33, 34, 15, 13, 32, 24,  3, 12, 31,  6, 14,  4,  1,  0,
       26,  5,  9, 23, 19, 21, 11, 16, 25,  7, 20, 28, 10,  8, 30, 18, 27,
       22])

# Houston_BBVA
# This is all TYSY - no BIN given

In [22]:
print(datetime.now().strftime("%H:%M:%S"), "  --  Start reading Houston BBVA data")
Houston_BBVA_2019 = pd.read_excel(share_path + 'Houston BBVA Processing 2019.xlsx', sheet_name ='Sheet 1', #old: Houston_BBVA_Processing_by_Month.xlsx
                    converters={'Month':str, 'MID':str})
Houston_BBVA_2020 = pd.read_excel(share_path + 'Houston BBVA Processing 2020.xlsx', sheet_name ='Sheet 1', #old: Houston_BBVA_Processing_by_Month.xlsx
                    converters={'Month':str, 'MID':str})
Houston_BBVA_2021 = pd.read_excel(share_path + 'Houston BBVA Processing 2021.xlsx', sheet_name ='Sheet 1', #old: Houston_BBVA_Processing_by_Month.xlsx
                    converters={'Month':str, 'MID':str})

#Houston BBVA Processing 2021.xlsx and 2020

10:09:00   --  Start reading Houston BBVA data

In [23]:
Houston_BBVA = pd.concat([Houston_BBVA_2019, Houston_BBVA_2020, Houston_BBVA_2021], axis=0)  #add

In [24]:
Houston_BBVA_1 = Houston_BBVA.copy()
Houston_BBVA_1 = Houston_BBVA_1.rename(columns={
                            #"ACCOUNT_ID":"MID",
                            #"MerchantDBA": "Business DBA Name", 
                            #"MerchantLegal": "Business Legal Name",
                            "Current Status": "current Status",
                            #"Partner": "Partner DBA",
                            #"Office": "Office Name",
                            #"AcquiringBank": "Bank", 
                            #"BUSINESSCOUNTRY": "Business Country", 
                            "BusinessGroup" : "Business Group", 
                            "Month":"YM", 
                            "Credit Decision Date":"Active Month Max",  #Would prefer first process date but don't have it
                            #"INACTIVE_MONTH_MAX":"Inactive Month Max",
                            "Cancel Month":"Cancel Month Max",
                            "CC Avg Ticket":"CC Avg Ticket Value",
                            #"CCApprovedVolume":"CU Approved Volume",
                            #"CP/CNPMerchant":"Payment Category", 
                            #"VisaSaleCount":"Sales Count",
                            #"VisasSaleAmount":"Sales Volume",
                            "Return Count":"Refund Count",
                            "Return Volume":"Refund Volume", 
                            #"Chargebackcount":"CB Count", 
                            #"ChargebackAmount":"CB Volume",
                            #"ClosureReason": "Closure Reason Name" #not available
                           })



#Houston_BBVA_1 = Houston_BBVA_1.drop(columns=['ISV_PARTNER_NAME'])

Houston_BBVA_1["Active Month Max"] = Houston_BBVA_1["Active Month Max"].dt.strftime('%Y') + Houston_BBVA_1["Active Month Max"].dt.strftime('%m')
Houston_BBVA_1["Cancel Month Max"] = Houston_BBVA_1["Cancel Month Max"].dt.strftime('%Y') + Houston_BBVA_1["Cancel Month Max"].dt.strftime('%m')


#Flags
Houston_BBVA_1["Activation Flag"] = (Houston_BBVA_1["Active Month Max"] == Houston_BBVA_1["YM"]).astype('int')
#Houston_BBVA_1["Inactive Flag -1"] = 
Houston_BBVA_1["Cancelation Flag"] = (Houston_BBVA_1["Cancel Month Max"] == Houston_BBVA_1["YM"]).astype('int')
Houston_BBVA_1["Cancelation Flag -1"] = (Houston_BBVA_1["Cancel Month Max"] == Houston_BBVA_1["YM"]).astype('int')*-1

Houston_BBVA_1["Actively Processing"] = (Houston_BBVA_1['Sales Volume'] >= 50).astype('int')
Houston_BBVA_1['Tenure_Months'] = Houston_BBVA_1[["MID", "Actively Processing"]].groupby('MID').transform('sum')

Houston_BBVA_1['Business Country'] = 'US'
Houston_BBVA_1['Business Group'] = 'MCPS'
Houston_BBVA_1['Bank'] = 'BBVA'
Houston_BBVA_1['Month'] = pd.to_datetime(Houston_BBVA_1['YM'].str[0:4] + '-' + Houston_BBVA_1['YM'].str[4:6]+  '-01')
#Houston_BBVA_1['Refund Volume'] = Houston_BBVA_1['Refund Volume']*-1
#Houston_BBVA_1['CB Volume'] = Houston_BBVA_1['CB Volume']*-1


status_dict_Houston_BBVA = {#nan:'MS - Active', gets handled by replace(np.nan...
                            'V':'Diverted', 
                            'C':'Cancelled', 
                            'C,V':'Cancelled', 
                            'V,C':'Cancelled', 
                            'S':'Active'}

Houston_BBVA_1['current Status'] = Houston_BBVA_1['current Status'].replace(status_dict_Houston_BBVA)
Houston_BBVA_1['current Status'] = Houston_BBVA_1['current Status'].replace(np.nan, 'Active', regex=True)
Houston_BBVA_1

,MID,Business DBA Name,Business Legal Name,current Status,MCC,Partner DBA,Bank,Office Name,Active Month Max,Cancel Month Max,CC Avg Ticket Value,CU Approved Volume,YM,Sales Count,Sales Volume,Refund Count,Refund Volume,Activation Flag,Cancelation Flag,Cancelation Flag -1,Actively Processing,Tenure_Months,Business Country,Business Group,Month
0,220000019,COMPASS BANK,COMPASS BANK,Active,6010,BBVA,BBVA,Houston,197610,NaN,NaN,NaN,201911,28,16172.23,0,0.0,0,0,0,1,24,US,MCPS,2019-11-01
1,220000019,COMPASS BANK,COMPASS BANK,Active,6010,BBVA,BBVA,Houston,197610,NaN,NaN,NaN,201912,26,8999.50,0,0.0,0,0,0,1,24,US,MCPS,2019-12-01
2,220000043,BBVA COMPASS BELTLINE RD,BBVA COMPASS BELTLINE RD,Active,6010,BBVA,BBVA,Houston,197610,NaN,NaN,NaN,201911,69,37755.57,0,0.0,0,0,0,1,24,US,MCPS,2019-11-01
3,220000043,BBVA COMPASS BELTLINE RD,BBVA COMPASS BELTLINE RD,Active,6010,BBVA,BBVA,Houston,197610,NaN,NaN,NaN,201912,80,46818.12,0,0.0,0,0,0,1,24,US,MCPS,2019-12-01
4,220001694,COMPASS GOVERNORS DR,COMPASS GOVERNORS DR,Active,6010,BBVA,BBVA,Houston,197610,NaN,NaN,NaN,201911,37,19267.99,0,0.0,0,0,0,1,23,US,MCPS,2019-11-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17290,220379581,BBVA COMPASS,BBVA COMPASS,Active,6010,BBVA,BBVA,Houston,200101,NaN,NaN,NaN,202101,7,11055.88,0,0.0,0,0,0,1,23,US,MCPS,2021-01-01
17291,221172115,DANCE ET CETERA,DANCE ET CETERA LLC,Active,7911,BBVA Portfolio Purchase 2018,BBVA,Houston,201408,NaN,44.42,8000.00,202101,75,8062.67,0,0.0,0,0,0,1,23,US,MCPS,2021-01-01
17292,220510971,LAWRENCE A WRIGHT MD,LAWRENCE A WRIGHT MD,Active,8043,BBVA Portfolio Purchase 2018,BBVA,Houston,200409,NaN,10.00,29166.67,202101,2,310.90,1,212.0,0,0,0,1,24,US,MCPS,2021-01-01
17293,221072471,CORRAL TRAN SINGH,CORRAL TRAN SINGH LLP,Active,8111,BBVA Portfolio Purchase 2018,BBVA,Houston,201205,NaN,1500.00,40000.00,202101,5,5510.00,0,0.0,0,0,0,1,25,US,MCPS,2021-01-01
17294,220553549,HOTEL LIQUIDATORS,GARY S WILLIAMS,Active,5712,BBVA Portfolio Purchase 2018,BBVA,Houston,200505,NaN,2611.54,8333.33,202101,3,12000.00,0,0.0,0,0,0,1,10,US,MCPS,2021-01-01

In [25]:
Houston_BBVA_1['current Status'].unique()

array(['Active', 'Cancelled', 'Diverted'], dtype=object)

# Houston_WF

In [26]:
#Houston_WF is in primus SQL 
print(datetime.now().strftime("%H:%M:%S"), "  --  Start reading Houston WF data")
Houston_WF = pd.read_csv(local_path + 'Houston WF_Portfolio_Processing rev 1.0.csv'
            , dtype={'Month' : 'str'})

10:09:25   --  Start reading Houston WF data

In [27]:
Houston_WF_1 = Houston_WF.copy()
#Houston_WF_1 = Houston_WF_1.loc[~Houston_WF_1['Month'].isna()]
Houston_WF_1 = Houston_WF_1.rename(columns={"Month":"YM"})
Houston_WF_1['Month'] = pd.to_datetime(Houston_WF_1['Date'])
Houston_WF_1['Business Country'] = 'US'
Houston_WF_1['Business Group'] = 'MCPS'
Houston_WF_1 = Houston_WF_1.drop(columns=['Date'])

status_dict_Houston_WF_1 = {'MS - Cancellation':'Cancelled', 'MS - Active':'Active'}
Houston_WF_1['current Status'] = Houston_WF_1['current Status'].replace(status_dict_Houston_WF_1)

#Houston_WF_1 = Houston_WF_1.drop(columns=['Activation Flag.1']) #can remove the duplicate column from the SQL
Houston_WF_1

,MID,Business DBA Name,Business Legal Name,current Status,MCC,Partner DBA,Bank,BIN,Office Name,Active Month Max,Inactive Month Max,Cancel Month Max,CC Avg Ticket Value,CU Approved Volume,Payment Category,YM,Sales Count,Sales Volume,Refund Count,Refund Volume,CB Count,CB Volume,Fraud Volume,Fraud Count,Activation Flag,Activation Flag.1,Inactive Flag -1,Cancelation Flag,Cancelation Flag -1,Actively Processing,Tenure_Months,Month,Business Country,Business Group
0,296201636887,ABSOLUTE PROCESS INSTRUMENTS INC,ABSOLUTE PROCESS INSTRUMENTS I,Active,5999,CBS06,Woodforest,296201,Houston,201505,NaN,NaN,NaN,NaN,NaN,202102,58.0,54199.69,NaN,NaN,NaN,NaN,will add,will add,0,0,0,0,0,1,34,2021-02-01,US,MCPS
1,296201636887,ABSOLUTE PROCESS INSTRUMENTS INC,ABSOLUTE PROCESS INSTRUMENTS I,Active,5999,CBS06,Woodforest,296201,Houston,201505,NaN,NaN,NaN,NaN,NaN,201904,83.0,63285.92,1.0,337.0,NaN,NaN,will add,will add,0,0,0,0,0,1,34,2019-04-01,US,MCPS
2,296201636887,ABSOLUTE PROCESS INSTRUMENTS INC,ABSOLUTE PROCESS INSTRUMENTS I,Active,5999,CBS06,Woodforest,296201,Houston,201505,NaN,NaN,NaN,NaN,NaN,201906,67.0,53557.89,2.0,2152.0,NaN,NaN,will add,will add,0,0,0,0,0,1,34,2019-06-01,US,MCPS
3,296201636887,ABSOLUTE PROCESS INSTRUMENTS INC,ABSOLUTE PROCESS INSTRUMENTS I,Active,5999,CBS06,Woodforest,296201,Houston,201505,NaN,NaN,NaN,NaN,NaN,202007,49.0,33735.36,1.0,300.0,NaN,NaN,will add,will add,0,0,0,0,0,1,34,2020-07-01,US,MCPS
4,296201636887,ABSOLUTE PROCESS INSTRUMENTS INC,ABSOLUTE PROCESS INSTRUMENTS I,Active,5999,CBS06,Woodforest,296201,Houston,201505,NaN,NaN,NaN,NaN,NaN,202109,54.0,80183.50,2.0,2256.0,NaN,NaN,will add,will add,0,0,0,0,0,1,34,2021-09-01,US,MCPS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1493050,5482986000100146,BELTONE MODESTO,DENNIS THOMAS,Active,5975,"Merchants Bancard Network, Inc",Woodforest,548298,Houston,201308,NaN,NaN,NaN,NaN,NaN,202006,33.0,21882.50,NaN,NaN,NaN,NaN,will add,will add,0,0,0,0,0,1,34,2020-06-01,US,MCPS
1493051,5482986000100146,BELTONE MODESTO,DENNIS THOMAS,Active,5975,"Merchants Bancard Network, Inc",Woodforest,548298,Houston,201308,NaN,NaN,NaN,NaN,NaN,201912,19.0,16522.62,1.0,750.0,NaN,NaN,will add,will add,0,0,0,0,0,1,34,2019-12-01,US,MCPS
1493052,5482986000100146,BELTONE MODESTO,DENNIS THOMAS,Active,5975,"Merchants Bancard Network, Inc",Woodforest,548298,Houston,201308,NaN,NaN,NaN,NaN,NaN,202101,20.0,7370.00,NaN,NaN,NaN,NaN,will add,will add,0,0,0,0,0,1,34,2021-01-01,US,MCPS
1493053,5482986000100146,BELTONE MODESTO,DENNIS THOMAS,Active,5975,"Merchants Bancard Network, Inc",Woodforest,548298,Houston,201308,NaN,NaN,NaN,NaN,NaN,202107,30.0,33510.00,1.0,1650.0,NaN,NaN,will add,will add,0,0,0,0,0,1,34,2021-07-01,US,MCPS
1493054,5482986000100146,BELTONE MODESTO,DENNIS THOMAS,Active,5975,"Merchants Bancard Network, Inc",Woodforest,548298,Houston,201308,NaN,NaN,NaN,NaN,NaN,202004,22.0,6477.00,NaN,NaN,NaN,NaN,will add,will add,0,0,0,0,0,1,34,2020-04-01,US,MCPS

In [28]:
Houston_WF_1['current Status'].unique()

array(['Active', 'Cancelled'], dtype=object)

# MCC Groups

In [29]:
MCC_group = pd.WLV = pd.read_excel(share_path + 'MCC Group Map.xlsx', sheet_name = 'Sheet1') ## might break if Ben adds columns

In [30]:
MCC_group

,MCC,MCC Group,MCC Description
0,742,Other Business Services,VETERINARY SERVICES
1,763,Other Business Services,AGRICULTURAL COOPERATIVES
2,780,Maintenance & Repair,LANDSCAPING AND HORTICULTURAL SERVICES
3,1520,Maintenance & Repair,GENERAL CONTRACTORS-RESIDENTIAL BUILDINGS
4,1711,Maintenance & Repair,HEATING PLUMBING AIR CONDITIONING CONTRACTORS
...,...,...,...
898,3816,"Travel, Airlines, Rental and Ticketing",HOME2SUITES
899,7231,Other Business Services,BEAUTY SHOPS AND BARBER SHOPS
900,7539,Maintenance & Repair,AUTO REPAIR (NON-DEALER)
901,8221,"Health, Legal, Government & Education",COLLEGES UNIV PRO SCHOOLS JUNIOR COLLEGES
902,5423,Retail / Tangible Goods,FREEZER LOCKER MEAT PROVISIONERS

# Concat Offices

In [31]:
merge_1 = pd.concat([Irvine_1, UK_Montreal_1, WLV_1, Houston_BBVA_1, Houston_WF_1], axis=0)  #add 
merge_1.reset_index()

bank_dict_merge_1 = {'Merrick Bank': 'MER'}
merge_1['Bank'] = merge_1['Bank'].replace(bank_dict_merge_1)
merge_1 = merge_1.merge(MCC_group, on='MCC', how='left')
merge_1

,MID,Business DBA Name,Business Legal Name,current Status,MCC,CRM_VendorUID,Partner DBA,Bank,BIN,Office Name,Active Month Max,Inactive Month Max,Cancel Month Max,CC Avg Ticket Value,CU Approved Volume,Payment Category,Closure Reason Name,Closure Reason Description,YM,Sales Count,Sales Volume,Refund Count,Refund Volume,CB Count,CB Volume,Fraud Volume,Fraud Count,Activation Flag,Activation Flag.1,Inactive Flag -1,Cancelation Flag,Cancelation Flag -1,Actively Processing,Tenure_Months,Reserve Amount,Month,Business Country,Business Group,ISV_PARTNER_NAME,ISO,SalesAgent,MCC Group,MCC Description
0,3286000000008060,Active Ride Shop 1002,Active Sports Lifestyle USA LLC,Cancelled,5699.0,NaN,Pro Music Group,Woodforest,328600.0,Irvine (US),201206,NaN,201506,70.0,200000,CNP,Inadequate Products/Services,Products or services are unable to accommodate...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,will add,will add,0,0.0,0.0,0,0,0,0,NaN,NaT,US,Meritus,NaN,NaN,NaN,Retail / Tangible Goods,MISCELLANEOUS APPAREL AND ACCESSORY STORES
1,3286000000008094,Two Trees Inn,Mashantucket Pequot Gaming Enterprise,Cancelled,7011.0,NaN,Primary Merchant Solutions,Woodforest,328600.0,Irvine (US),201211,NaN,201703,500.0,375000,CP,Risk - Collections,"Collections due to chargebacks, credits, fees,...",201601,1507.0,260529.73,47.0,6000.07,3.0,226.18,will add,will add,0,0.0,0.0,0,0,1,5,NaN,2016-01-01,US,Meritus,NaN,NaN,NaN,"Travel, Airlines, Rental and Ticketing",LODGING-HOTELS MOTELS RESORTS
2,3286000000008094,Two Trees Inn,Mashantucket Pequot Gaming Enterprise,Cancelled,7011.0,NaN,Primary Merchant Solutions,Woodforest,328600.0,Irvine (US),201211,NaN,201703,500.0,375000,CP,Risk - Collections,"Collections due to chargebacks, credits, fees,...",201602,1718.0,323940.25,16.0,1659.23,3.0,45.88,will add,will add,0,0.0,0.0,0,0,1,5,NaN,2016-02-01,US,Meritus,NaN,NaN,NaN,"Travel, Airlines, Rental and Ticketing",LODGING-HOTELS MOTELS RESORTS
3,3286000000008094,Two Trees Inn,Mashantucket Pequot Gaming Enterprise,Cancelled,7011.0,NaN,Primary Merchant Solutions,Woodforest,328600.0,Irvine (US),201211,NaN,201703,500.0,375000,CP,Risk - Collections,"Collections due to chargebacks, credits, fees,...",201603,1631.0,344404.09,41.0,4751.12,2.0,526.41,will add,will add,0,0.0,0.0,0,0,1,5,NaN,2016-03-01,US,Meritus,NaN,NaN,NaN,"Travel, Airlines, Rental and Ticketing",LODGING-HOTELS MOTELS RESORTS
4,3286000000008094,Two Trees Inn,Mashantucket Pequot Gaming Enterprise,Cancelled,7011.0,NaN,Primary Merchant Solutions,Woodforest,328600.0,Irvine (US),201211,NaN,201703,500.0,375000,CP,Risk - Collections,"Collections due to chargebacks, credits, fees,...",201604,1577.0,307170.60,34.0,4624.34,5.0,552.49,will add,will add,0,0.0,0.0,0,0,1,5,NaN,2016-04-01,US,Meritus,NaN,NaN,NaN,"Travel, Airlines, Rental and Ticketing",LODGING-HOTELS MOTELS RESORTS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4913285,5482986000100146,BELTONE MODESTO,DENNIS THOMAS,Active,5975.0,NaN,"Merchants Bancard Network, Inc",Woodforest,548298.0,Houston,201308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202006,33.0,21882.50,NaN,NaN,NaN,NaN,will add,will add,0,0.0,0.0,0,0,1,34,NaN,2020-06-01,US,MCPS,NaN,NaN,NaN,Retail / Tangible Goods,HEARING AIDS-SALES SERVICE SUPPLY STORES
4913286,5482986000100146,BELTONE MODESTO,DENNIS THOMAS,Active,5975.0,NaN,"Merchants Bancard Network, Inc",Woodforest,548298.0,Houston,201308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201912,19.0,16522.62,1.0,750.00,NaN,NaN,will add,will add,0,0.0,0.0,0,0,1,34,NaN,2019-12-01,US,MCPS,NaN,NaN,NaN,Retail / Tangible Goods,HEARING AIDS-SALES SERVICE SUPPLY STORES
4913287,5482986000100146,BELTONE MODESTO,DENNIS THOMAS,Active,5975.0,NaN,"Merchants Bancard Network, Inc",Woodforest,548298.0,Houston,201308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202101,20.0,7370.00,NaN,NaN,NaN,NaN,will add,will add,0,0.0,0.0,0,0,1,34,NaN,2021-01-01,US,MCPS,NaN,NaN,NaN,Retail / Tangible Goods,HEARING AIDS-SALES SERVICE SUPPLY STORES
4913288,5482986000100146,BELTONE MODESTO,DENNIS THOMAS,Active,5975.0,NaN,"Merchants Bancard Network, Inc",Woodforest,548298.0,Houston,201308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202107,30.0,33510.00,1.0,1650.00,NaN,NaN,will add,will add,0,0.0,0.0,0,0,1,34,NaN,2021-07-01,US,MCPS,NaN,NaN,NaN,Retail / Tangible Goods,HEARING AIDS-SALES SERVICE SUPPLY STORES
4913289,5482986000100146,BELTONE MODESTO,DENNIS THOMAS,Active,5975.0,NaN,"Merchants Bancard Network, Inc",Woodforest,548298.0,Houston,201308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202004,22.0,6477.00,NaN,NaN,NaN,NaN,will add,will add,0,0.0,0.0,0,0,1,34,NaN,2020-04-01,US,MCPS,NaN,NaN,NaN,Retail / Tangible Goods,HEARING AIDS-SALES SERVICE SUPPLY STORES

In [32]:
merge_1['current Status'].unique()

array(['Cancelled', 'Active', 'MS - Inactive',
       'MS - Conducted Welcome Call', 'Diverted'], dtype=object)

In [33]:
merge_1['Bank'].unique()

array(['Woodforest', 'BBVA', 'Headquarter', 'NMC', 'LL Group Wells Fargo',
       'Wells Meritus', 'ACH/DD Only', 'NCAL', 'TransNational',
       'BMO - Harris', 'MOC', 'PET', 'MER', 'VAN', 'AIB', 'BOV', 'OPL',
       'NAB', 'Wells Fargo'], dtype=object)

In [34]:
#local folder

print(datetime.now().strftime("%H:%M:%S"), "  --  Start local save")
merge_1.to_csv(local_path + "Global Merchant Portfolio_rev 10.0 add zeus CRM.csv") #, sheet_name='Data')
print(datetime.now().strftime("%H:%M:%S"), "  --  End local save")

10:10:33   --  Start local save
10:14:14   --  End local save

In [35]:
#share drive (R drive)

#print(datetime.now().strftime("%H:%M:%S"), "  --  Start shared drive save")
#merge_1.to_csv(share_path + "python_merge_9_added Houston.csv") #, sheet_name='Data')
#print(datetime.now().strftime("%H:%M:%S"), "  --  End shared drive save")

In [36]:
#import tkinter as tk 

#root= tk.Tk() 
 
#canvas1 = tk.Canvas(root, width = 300, height = 300)
#canvas1.pack()

#label1 = tk.Label(root, text="Done with python_merge_9_added Houston.csv")
#canvas1.create_window(150, 150, window=label1)

#root.mainloop()